name: Update README with Markscribe

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate README from Markscribe
        run: |
          curl -s "https://markscribe.dev/api/generate?template=https://gist.githubusercontent.com/kcoder3004/f853b58e61dc3a5188a1876abe963d5c/raw/de26418c36ced32ab1f47b13e250a762cfcf6f85/markscribe-template.md&data=%7B%22github%22%3A%22kcoder3004%22%7D" -o README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "chore: update README via Markscribe" || echo "No changes to commit"
          git push
