name: Update README with Markscribe and Hackatime Stats

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate README with Markscribe
        run: |
          curl -s "https://markscribe.dev/api/generate?template=https://gist.githubusercontent.com/kcoder3004/f853b58e61dc3a5188a1876abe963d5c/raw/de26418c36ced32ab1f47b13e250a762cfcf6f85/markscribe-template.md&data={\"github\":\"kcoder3004\"}" -o README.md

      - name: Fetch Hackatime Stats
        id: hackatime-stats
        run: |
          HACKATIME_API_URL="https://hackatime.hackclub.com/api/hackatime/v1"
          HACKATIME_API_KEY="${{ secrets.HACKATIME_API_KEY }}"  # Store your Hackatime API key as a secret

          # Fetch Hackatime stats using the API
          STATS=$(curl -s -H "Authorization: Bearer ${HACKATIME_API_KEY}" $HACKATIME_API_URL)

          # Extract the languages and projects (assuming Hackatime provides this data in the response)
          LANGUAGES=$(echo $STATS | jq -r '.languages | map(.name) | join(", ")')
          PROJECTS=$(echo $STATS | jq -r '.projects | map(.name) | join(", ")')

          # Generate the custom category bar for the README
          LANGUAGES_BAR="💾 Languages: $LANGUAGES"
          PROJECTS_BAR="💼 Projects: $PROJECTS"

          # Set these variables to be used in the README
          echo "LANGUAGES_BAR=$LANGUAGES_BAR" >> $GITHUB_ENV
          echo "PROJECTS_BAR=$PROJECTS_BAR" >> $GITHUB_ENV

      - name: Update README with Hackatime Data
        run: |
          # Replace the placeholders in README with the generated data
          sed -i "s|{{ wakatimeDoubleCategoryBar \"💾 Languages:\" wakatimeData.Languages \"💼 Projects:\" wakatimeData.Projects 5 }}|${{ env.LANGUAGES_BAR }}\n${{ env.PROJECTS_BAR }}|g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with Hackatime stats" || echo "No changes to commit"
          git push origin main
